CREATE USER EXPORT_USER IDENTIFIED BY "qwerty" DEFAULT
TABLESPACE FAR_BROWN_OVEN;
GRANT ALL PRIVILEGES to EXPORT_USER identified by "qwerty";
GRANT IMP_FULL_DATABASE to EXPORT_USER;
GRANT EXP_FULL_DATABASE to EXPORT_USER;
GRANT DATAPUMP_IMP_FULL_DATABASE to EXPORT_USER;
GRANT DATAPUMP_EXP_FULL_DATABASE to EXPORT_USER;
